var minify = require("html-minifier").minify;
var UglifyJS = require("uglify-js");

exports.setup = 
{
	on: true,
	reloadAll: true,
}

function minifyIt(_src)
{
    return minify(_src, 
    {
	  includeAutoGeneratedTags: false,
	  removeComments: true,
	  trimCustomFragments: true,
	  removeEmptyLines: true,
	  collapseWhitespace: true,
	  collapseBooleanAttributes: true,
	  decodeEntities: true,
	  minifyJS: true,
	  minifyCSS: true,
	});
}

async function stripHtml(_obj)
{
    if(_obj.event == "instance.forge.main")
    {
        _obj.data = minifyIt(_obj.data);
    }
    else if(_obj.event == "instance.load.theme")
    {
        for(var d in _obj.data)
    	{
    		try 
    		{
                if(typeof d == "string")
        		{
        			var _name = d.split(".");
        			if(_name[_name.length-1] == "js")
        			{
        				_obj.data[d] = UglifyJS.minify(_obj.data[d]).code;
        			}
        			else if(_name[_name.length-1] == "html")
        			{
        				_obj.data[d] = minifyIt(_obj.data[d]);
        			}
        		}
    		}catch(e){}
    	}
    }
	else if(_obj.event == "instance.load.route")
    {
		for(var d in _obj.data)
    	{
    		try 
    		{
    			_obj.data[d].body = minifyIt(_obj.data[d].body);
    		}catch(e){}
    	}
	}
    else 
    {
    	for(var d in _obj.data)
    	{
    		try 
    		{
    			_obj.data[d] = minifyIt(_obj.data[d]);
    		}catch(e){}
    	}
    }
}

exports.event = 
{
	
    "instance.forge.main":
    {
	    position: 0,
	    on: true,
	    handler: stripHtml,
	},
	"instance.load.route":
	{
		position: 0,
	    on: true,
	    handler: stripHtml,
	},
}
